<?php

namespace FMW\Utilities\Validation;

/** 
 * 
 * Class Validation
 *
 * @author Hugo Mastromauro <hugomastromauro@gmail.com>
 * @version 0.1 
 * @copyright  GPL © 2010, hugomastromauro.com. 
 * @access public  
 * @package FMW 
 * @subpackage lib
 *  
 */  
class Validation
	implements \FMW\Utilities\Validation\IValidation {
	
	/**      
     * Array of all errors generated by the validation 
     * @access private 
     * @name $_errors
     * @var array 
     */ 
	private $_errors = array();
	
	/**      
     * Array with all data loaded for viewing post
     * @access private 
     * @name $_data
     * @var array 
     */ 
	private $_data = array();	
	
	/**      
     * Array that loads all configuration messages
     * @access private 
     * @name $_messages
     * @var array 
     */ 
	private $_messages = array();
	
	/**      
     * Array that carries all the validation rules
     * @access private 
     * @name $_rules
     * @var array 
     */ 
	private $_rules = array();
	
	/**      
     * Object Request
     * @access private 
     * @name $_request
     * @var object 
     */ 
	private $_request;
	
	/**      
     * Variable that sets the return of the validation
     * @access private 
     * @name $success
     * @var bool 
     */ 
	private	$_success = true;
	
	/** 
     * Class constructor that loads the validation settings
     * @access public 
     * @param array $rules
     * @param array $messages    
     * @return void 
     */ 
  	public function __construct ( array $rules, array $messages, \FMW\Application\Request\Request $request = null ) {
  		
		$this->_rules = $rules;
		$this->_messages = $messages;
		$this->_request = $request;
	}
	
	/** 
     * Method that validates the form
     * @access public        
     * @return void 
     */
	public function validate() {
						
		foreach( $this->_rules as $field => $value ) {
						
			if (isset($_FILES[$field])) 
			{								
				$value = $_FILES[$field];				
			} 
			else 
			{
				if (isset($this->_request)) {														
					$value = $this->_request->$field;						
				}else{
					$value = is_string( $_REQUEST[$field] ) ?  $this->sanitize( $_REQUEST[$field] ) : $_REQUEST[$field];
				}
			}
			
			$this->setData( $value, $field );
		}
		
		foreach( $this->_rules as $field => $value ) {
			
			if ( is_array($value['rules']) ) {

				foreach( $value['rules'] as $newValue ) {
					
					if ( is_object($newValue) ) {
						
						$this->validateObject( $field, $value, $newValue );
						
					} else {
						
						$this->validateFunction( $field, $newValue );
					}
				}
				
			} else {													
				
				if ( is_object( $value['rules'] ) ) {
					
					$this->validateObject( $field, $value, $value['rules'] );
					
				} else {
					
					$this->validateFunction( $field, $value );
				}
			}
		}

		return $this->_success;
	}
	
	/**
	 * 
	 * Enter description here ...
	 * @access private
	 * @param string $field
	 * @param array $value
	 * @param FMW\Utilities\Validation\ARules $value
	 * @return void
	 */
	private function validateObject( $field, array $value, \FMW\Utilities\Validation\ARules $obj ) {
		
		$obj->setValidation($this);
		
		if (!(is_callable(array($obj, $obj->getMethod())))) 
			throw new \FMW\Utilities\Validation\Exception('Método não encontrado!');
		
		if (!call_user_func(array($obj, $obj->getMethod()), $this->getData($field), $field, $obj->getParams()))
		{			
			if (!isset($this->_messages['error'][$obj->getMethodError()])) 
				throw new \FMW\Utilities\Validation\Exception('Mensagem de erro não definida!');
			
			$this->_success = false;
			$this->setError($this->_messages['error'][$obj->getMethodError()], $field, $value['label'], $value);
		}
	}
	
	/**
	 * 
	 * Enter description here ...
	 * @access private
	 * @param string $field
	 * @param array $value
	 * @return void
	 */
	private function validateFunction( $field, array $value ) {
		
		$label = $value['label'];
		$rules = $value['rules'];
							
		$value = $this->getData($field);
		$check = preg_split('/\|/', $rules);					

		foreach ($check as $function)
		{
			$callback = NULL;					
			
			if (preg_match("/:/i", $function))
			{									
				list($function, $callback) = explode(":", $function);				
			}							
			
			if (strpos($function, '[') !== FALSE AND preg_match_all('/\[(.*?)\]/', $function, $matches))
			{
				$x = explode('[', $function);
				$function = current($x);

				for ($x = 0; $x < count($matches['0']); $x++)
				{						
					if ($matches['1'][$x] != '')
					{
						if (isset($_POST[$matches['1'][$x]]))
						{
							$params[] = $this->getData($matches['1'][$x]);
						}
						else
						{
							$param = str_ireplace("'", '', $matches['1'][$x]);
							$param = str_ireplace('"', '', $matches['1'][$x]);
							$params[] = $param;
						}
					}
				}
			}				

			if (strpos($callback, '[') !== FALSE AND preg_match_all('/\[(.*?)\]/', $callback, $matches))
			{
				$x = explode('[', $callback);
				$callback = current($x);
				
				for ($x = 0; $x < count($matches['0']); $x++)
				{											
					if ($matches['1'][$x] != '')
					{
						if (isset($_POST[$matches['1'][$x]]))
						{
							$params[] = $this->getData($matches['1'][$x]);
						}
						else
						{
							$param = str_ireplace("'", '', $matches['1'][$x]);
							$param = str_ireplace('"', '', $matches['1'][$x]);	
							$params[] = $param;
						}
					}
				}
			}
			
			if (!isset($params)) $params = NULL;
				
			if (is_callable(array($this, $function)))
			{												
				if (call_user_func(array($this, $function), $value, $field, $params))
				{																
					$this->callback($this, $callback, $field, $label, $value);									
				}
				else
				{																
					$this->_success = false;
					$this->setError($this->_messages['error'][$function], $field, $label, $value);
				}
			}
			else
			{
				if ($function == 'required')
				{				
					if (!$this->getData($field) || $this->getData($field) == null)
					{															
						$this->_success = false;
						$this->setError($this->_messages['error']['required'], $field, $label, $value);
					}
					else
					{
						$this->callback($this, $callback, $field, $label, $value);							
					}
				}					
			}				
		}		
	}
	
	/** 
    * Validation method return
    * @access private 
    * @param object $obj
    * @param string $callback
    * @param string $field
    * @param string $label
    * @param string $value       
    * @return void 
    */
	private function callback($obj, $callback, $field, $label, $value) {
				
		if (is_callable(array($obj, $callback)))
		{															
			if (call_user_func(array($obj, $callback), $value, $field) == false)
			{								
				$this->_success = false;
				$this->setError($this->_messages['error'][$callback], $field, $label, $value);
			}
		}
	}
	
	/** 
     * Method that returns the status of validation
     * @access public     
     * @return bool 
     */
	public function success()
	{
		return $this->_success;
	}
	
	/** 
     * Method which sets the status of validation
     * @access public 
     * @param bool $bool       
     * @return void 
     */
	public function setSuccess($bool)
	{
		$this->_success = $bool;
	}
	
	/** 
     * Method that sets values in the array $data is valid
     * @access public 
     * @param string $value
     * @param string $field    
     * @return void 
     */
	public function setData($value, $field)
	{
		$this->_data[$field] = $value;
	}
	
	/** 
     * Method which sets the error level
     * @access public 
     * @param string $error
     * @param array $params    
     * @return void 
     */
	public function setLevelError($error, $params = null)
	{
		$msg = $this->_messages['error'][$error];
		
		if (is_array($params))
		{
			$this->errors_[$error] = array('message' => $this->printf_array($msg, $params));
		}
		else
		{
			$this->errors_[$error] = array('message' => $msg);
		}		
	}
	
	/** 
     * Method which sets the error
     * @access public 
     * @param string $msg
     * @param string $field
     * @param string $label
     * @param string $value
     * @param array $params    
     * @return void 
     */
	public function setError($msg, $field, $label, $value, $params = null)
	{
		if (is_array($params))
		{
			$this->_errors[$field] = array('message' => $this->printf_array($msg, array($label, $value, $params)));
		}
		else
		{
			$this->_errors[$field] = array('message' => sprintf($msg, $label, $value, $params));
		}
	}
	
	/** 
     * Method that displays the messages
     * @access protected 
     * @param string $format
     * @param array $arr           
     * @return string 
     */
	protected function printf_array($format, $arr)
	{
    	return call_user_func_array('printf', array_merge((array)$format, $arr));
	}
	
	/** 
     * Method that retrieves data from array $data
     * @access public     
     * @param string $field       
     * @return string 
     */
	public function getData($field)
	{
		return $this->_data[$field];
	}
	
	/** 
     * Method that retrieves all data from array $data
     * @access public 
     * @return array 
     */
	public function getAllData()
	{
		return $this->_data;
	}
	
	/** 
     * Method that retrieves error
     * @access public     
     * @param string $field    
     * @return string 
     */
	public function getError($field)
	{
		return $this->_errors[$field];
	}
	
	/** 
     * Method loads all the data from array $error
     * @access public     
     * @return array 
     */
	public function getAllError()
	{
		return $this->_errors;
	}	
	
	/** 
     * Método que previne ataques por injeção de códigos
     * @access private 
     * @param string $value          
     * @return mixed 
     */
	private function sanitize( $value )
	{		
		if ( !is_array( $value ) ) {
			//return filter_var( $value, FILTER_SANITIZE_SPECIAL_CHARS, FILTER_SANITIZE_MAGIC_QUOTES );
			return htmlentities($value, ENT_QUOTES, 'UTF-8');
		}
		
		foreach ($value as $k => $v ) {
			$value[$k] = $this->sanitize($v);
		}

		return $value;
	}
}
